<?php

namespace AppBundle\Repository;

/**
 * CourierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourierRepository extends \Doctrine\ORM\EntityRepository
{
}
