
sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

        # Some block with different templates
        app.block.service.calendar: ~
        #acme.demo.block.demo:
        #    templates:
        #       - { name: 'Simple', template: 'AcmeDemoBundle:Block:demo_simple.html.twig' }
        #       - { name: 'Big',    template: 'AcmeDemoBundle:Block:demo_big.html.twig' }

twig:
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'

services:
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Category }

    admin.task:
        class: AppBundle\Admin\TaskAdmin
        arguments: [~, AppBundle\Entity\Task, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Task }

    admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [~, AppBundle\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Contact }

    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Product }

    app.admin.warranty_provider:
        class: AppBundle\Admin\WarrantyProviderAdmin
        arguments: [~, AppBundle\Entity\WarrantyProvider, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: WarrantyProvider }


    app.admin.repairer:
        class: AppBundle\Admin\RepairerAdmin
        arguments: [~, AppBundle\Entity\Repairer, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Repairer }


    app.admin.courier:
        class: AppBundle\Admin\CourierAdmin
        arguments: [~, AppBundle\Entity\Courier, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Courier }

    app.admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [~, AppBundle\Entity\Customer, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Customer }

    app.block.service.calendar:
        class: AppBundle\Block\CalendarBlock
        arguments:
            - app.block.service.calendar
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: sonata.block }

sonata_admin:
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: app.block.service.calendar