services:
    # ...
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.task:
        class: AppBundle\Admin\TaskAdmin
        arguments: [~, AppBundle\Entity\Task, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Task }

    admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [~, AppBundle\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Contact }

sonata_admin:
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig